using System;
using System.Collections.Generic;
using System.Drawing;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Xml.Linq;

namespace SaturnApp {
public class Settings {
 public bool Recursive=true, MinimizeOnPlay=false;
 public Settings Copy(){var s=(Settings)MemberwiseClone();s.Folders=Folders.ToList();return s;}
 public string BiosJapan="",BiosUsa="",BiosEurope="",BiosRegion="auto",DefaultRegion="JP";
 public string Language="en"; public bool SetupComplete=false; public string Engine="", Bios=""; public bool Hle=false, Fullscreen=true; public List<string> Folders=new List<string>();
 public void Save(string path) { var x=new XElement("Saturn",new XAttribute("biosJapan",BiosJapan),new XAttribute("biosUsa",BiosUsa),new XAttribute("biosEurope",BiosEurope),new XAttribute("biosRegion",BiosRegion),new XAttribute("defaultRegion",DefaultRegion),new XAttribute("recursive",Recursive),new XAttribute("minimizeOnPlay",MinimizeOnPlay),new XAttribute("language",L.Normalize(Language)),new XAttribute("setupComplete",SetupComplete),new XAttribute("engine",Engine),new XAttribute("bios",Bios),new XAttribute("hle",Hle),new XAttribute("fullscreen",Fullscreen),Folders.Select(f=>new XElement("Folder",f))); var tmp=path+".tmp"; x.Save(tmp); if(File.Exists(path)) File.Replace(tmp,path,path+".bak"); else File.Move(tmp,path); }
 public static Settings Load(string path) {var s=new Settings(); if(!File.Exists(path))return s; var x=XElement.Load(path);s.BiosJapan=(string)x.Attribute("biosJapan")??"";s.BiosUsa=(string)x.Attribute("biosUsa")??"";s.BiosEurope=(string)x.Attribute("biosEurope")??"";s.BiosRegion=(string)x.Attribute("biosRegion")??"auto";s.DefaultRegion=(string)x.Attribute("defaultRegion")??"JP";if(!new[]{"auto","JP","US","EU"}.Contains(s.BiosRegion))s.BiosRegion="auto";if(!new[]{"JP","US","EU"}.Contains(s.DefaultRegion))s.DefaultRegion="JP";s.Recursive=(bool?)x.Attribute("recursive")??true;s.MinimizeOnPlay=(bool?)x.Attribute("minimizeOnPlay")??false;s.Language=L.Normalize((string)x.Attribute("language")??"fr");s.SetupComplete=(bool?)x.Attribute("setupComplete")??false;s.Engine=(string)x.Attribute("engine")??"";s.Bios=(string)x.Attribute("bios")??"";s.Hle=(bool?)x.Attribute("hle")??false;s.Fullscreen=(bool?)x.Attribute("fullscreen")??true;s.Folders=x.Elements("Folder").Select(e=>e.Value).ToList();return s;}
}
public class Game {public string Path; public string Title {get{return System.IO.Path.GetFileNameWithoutExtension(Path);}}}
public static class Library {
 public static List<Game> Scan(IEnumerable<string> folders,List<string> errors,bool recursive=true) {var found=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var seen=new HashSet<string>(StringComparer.OrdinalIgnoreCase);var stack=new Stack<string>(folders);while(stack.Count>0){string dir=stack.Pop();try {dir=System.IO.Path.GetFullPath(dir);if(!seen.Add(dir))continue;if(!Directory.Exists(dir)){errors.Add(L.T("Missing folder: ")+dir);continue;}foreach(var f in Directory.GetFiles(dir)){var ext=System.IO.Path.GetExtension(f).ToLowerInvariant();if(ext==".cue"||ext==".iso"||ext==".chd") found.Add(f);}if(recursive)foreach(var d in Directory.GetDirectories(dir))if((File.GetAttributes(d)&FileAttributes.ReparsePoint)==0)stack.Push(d);}catch(Exception e){if(!(e is IOException)&&!(e is UnauthorizedAccessException)&&!(e is ArgumentException))throw;errors.Add(dir+" : "+e.Message);}}return found.Select(f=>new Game{Path=f}).OrderBy(g=>g.Title,StringComparer.CurrentCultureIgnoreCase).ToList();}
 public static void Validate(string path) {if(!File.Exists(path))throw new IOException(L.T("Game image not found: ")+path);if(System.IO.Path.GetExtension(path).Equals(".cue",StringComparison.OrdinalIgnoreCase)){var matches=Regex.Matches(File.ReadAllText(path),"^\\s*FILE\\s+(?:\"([^\"]+)\"|(\\S+))",RegexOptions.Multiline|RegexOptions.IgnoreCase);if(matches.Count==0)throw new IOException(L.T("The CUE file contains no FILE tracks."));foreach(Match m in matches){var track=m.Groups[1].Success?m.Groups[1].Value:m.Groups[2].Value;var full=System.IO.Path.GetFullPath(System.IO.Path.Combine(System.IO.Path.GetDirectoryName(path),track));if(!File.Exists(full))throw new IOException(L.T("Missing track: ")+track+L.T("\nKeep the CUE file and its tracks together."));}}}
}
public static class Engine {
 public static string Quote(string value){if(value.IndexOf('"')>=0||value.IndexOf('\n')>=0||value.IndexOf('\r')>=0)throw new ArgumentException(L.T("Invalid path."));return "\""+value+"\"";}
 public static string Arguments(Settings s,string game){return "--autostart --iso="+Quote(game)+(s.Hle?" --no-bios":" --bios="+Quote(RegionalBios.Select(s,game)))+(s.Fullscreen?" --fullscreen":"");}
 public static ProcessStartInfo StartInfo(Settings s,string game){if(!File.Exists(s.Engine))throw new IOException(L.T("Kronos is missing. Reinstall Segata Sakura."));Library.Validate(game);return new ProcessStartInfo(s.Engine,Arguments(s,game)){UseShellExecute=false,WorkingDirectory=System.IO.Path.GetDirectoryName(s.Engine)};}
}
public class MainForm:Form {
 static readonly Color Base=Color.FromArgb(35,37,33),Panel=Color.FromArgb(48,50,44),Gold=Color.FromArgb(204,182,119),Ink=Color.FromArgb(244,241,231);
 readonly string root=AppDomain.CurrentDomain.BaseDirectory;Settings settings;List<Game> games=new List<Game>();FlowLayoutPanel cards;TextBox search;Label status;Button scan;Process playing;bool scanning;string settingsPath;string data;ToolTip tips=new ToolTip();
 public MainForm(){var iconPath=System.IO.Path.Combine(root,"sakura-v022.ico");if(File.Exists(iconPath))Icon=new Icon(iconPath);Text=L.T("Segata Sakura — library · Kronos");Size=new Size(1100,760);MinimumSize=new Size(760,560);StartPosition=FormStartPosition.CenterScreen;BackColor=Base;ForeColor=Ink;Font=new Font("Segoe UI",10);AutoScaleMode=AutoScaleMode.Dpi;data=AppPaths.Initialize(root);settingsPath=System.IO.Path.Combine(data,"settings.xml");try{settings=Settings.Load(settingsPath);}catch(Exception e){settings=new Settings();Shown+=(a,b)=>MessageBox.Show(this,L.T("Unreadable settings: ")+e.Message+L.T("\nThe existing file is kept until your next save."));}var portable=System.IO.Path.Combine(root,"engine","kronos.exe");if(File.Exists(portable))settings.Engine=portable;
 var shell=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=1,RowCount=4,Margin=Padding.Empty,Padding=Padding.Empty};shell.RowStyles.Add(new RowStyle(SizeType.Absolute,104));shell.RowStyles.Add(new RowStyle(SizeType.Absolute,100));shell.RowStyles.Add(new RowStyle(SizeType.Percent,100));shell.RowStyles.Add(new RowStyle(SizeType.Absolute,34));Controls.Add(shell);
 var header=new System.Windows.Forms.Panel{Dock=DockStyle.Fill,BackColor=Gold,Margin=Padding.Empty};shell.Controls.Add(header,0,0);var logo=new PictureBox{Location=new Point(22,12),Size=new Size(70,78),SizeMode=PictureBoxSizeMode.Zoom};var logoPath=System.IO.Path.Combine(root,"sakura-logo.png");if(File.Exists(logoPath))logo.Image=Image.FromFile(logoPath);header.Controls.Add(logo);header.Controls.Add(new Label{Text="SEGATA SAKURA",Font=new Font("Georgia",27),ForeColor=Base,Location=new Point(108,15),AutoSize=true});header.Controls.Add(new Label{Text=L.T("YOUR COLLECTION · YOUR WORLD"),ForeColor=Base,Location=new Point(111,65),AutoSize=true,Font=new Font("Segoe UI",9)});
 var config=Button(L.T("Settings"),(a,b)=>Configure());config.Anchor=AnchorStyles.Right|AnchorStyles.Top;config.Location=new Point(870,30);header.Controls.Add(config);header.Resize+=(a,b)=>config.Left=header.Width-config.Width-24;
 var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(18,10,12,5),WrapContents=true,Margin=Padding.Empty};shell.Controls.Add(bar,0,1);bar.Controls.Add(Button(L.T("Open a game…"),(a,b)=>OpenGame()));bar.Controls.Add(Button(L.T("+ Folder"),(a,b)=>AddFolder()));scan=Button(L.T("Refresh"),(a,b)=>Scan());bar.Controls.Add(scan);search=new TextBox{Width=200,Margin=new Padding(16,7,8,0),BackColor=Panel,ForeColor=Ink,BorderStyle=BorderStyle.FixedSingle};search.AccessibleName=L.T("Search for a game");tips.SetToolTip(search,L.T("Search the library"));search.TextChanged+=(a,b)=>RenderGames();bar.Controls.Add(new Label{Text=L.T("Search"),AutoSize=true,Margin=new Padding(12,8,0,0)});bar.Controls.Add(search);
 cards=new FlowLayoutPanel{Dock=DockStyle.Fill,AutoScroll=true,Padding=new Padding(18),BackColor=Base,Margin=Padding.Empty};shell.Controls.Add(cards,0,2);status=new Label{Dock=DockStyle.Fill,Text=L.T("Kronos · ready to configure"),Padding=new Padding(20,6,0,0),BackColor=Panel,Font=new Font("Segoe UI",9)};shell.Controls.Add(status,0,3);Shown+=(a,b)=>Scan();FormClosing+=(a,b)=>{if(playing!=null&&!playing.HasExited)MessageBox.Show(this,L.T("The game remains open in Kronos."),"Segata Sakura");};}
 Button Button(string title,EventHandler action){var b=new Button{Text=title,AutoSize=true,Height=36,MinimumSize=new Size(100,36),FlatStyle=FlatStyle.Flat,BackColor=Panel,ForeColor=Ink,Padding=new Padding(8,2,8,2),Margin=new Padding(4)};b.FlatAppearance.BorderColor=Color.FromArgb(90,92,78);b.Click+=action;return b;}
 void Error(Exception e){status.Text=L.T("Action interrupted");MessageBox.Show(this,e.Message,"Segata Sakura",MessageBoxButtons.OK,MessageBoxIcon.Warning);}
 void AddFolder(){try{var folder=FolderPicker.Choose(this);if(folder==null)return;if(!settings.Folders.Contains(folder,StringComparer.OrdinalIgnoreCase))settings.Folders.Add(folder);settings.Save(settingsPath);Scan();}catch(Exception e){Error(e);}}
 void OpenGame(){using(var d=new OpenFileDialog{Title=L.T("Choose a Saturn game"),Filter=L.T("Saturn games|*.cue;*.iso;*.chd"),CheckFileExists=true,Multiselect=false})if(d.ShowDialog(this)==DialogResult.OK){var game=new Game{Path=d.FileName};try{Library.Validate(game.Path);var folder=System.IO.Path.GetDirectoryName(game.Path);if(!settings.Folders.Contains(folder,StringComparer.OrdinalIgnoreCase)){settings.Folders.Add(folder);settings.Save(settingsPath);Scan();}if(!RegionalBios.HasBios(settings)){MessageBox.Show(this,L.T("Select your Saturn BIOS in Settings to get started."),L.T("First launch"));Configure();if(!RegionalBios.HasBios(settings))return;}Launch(game);}catch(Exception e){Error(e);}}}
 async void Scan(){if(scanning)return;scanning=true;scan.Enabled=false;status.Text=L.T("Searching for games…");var errors=new List<string>();var dirs=settings.Folders.ToArray();try{games=await Task.Run(()=>Library.Scan(dirs,errors,settings.Recursive));RenderGames();status.Text=games.Count+L.T(" disc image(s) · ")+(errors.Count==0?L.T("Library refreshed"):errors.Count+L.T(" unreadable folder(s)"));if(errors.Count>0){File.WriteAllLines(System.IO.Path.Combine(data,"scan-errors.txt"),errors);tips.SetToolTip(status,string.Join("\n",errors.Take(4)));}}catch(Exception e){Error(e);}finally{scanning=false;scan.Enabled=true;}}
 void RenderGames(){cards.SuspendLayout();foreach(Control c in cards.Controls.Cast<Control>().ToArray()){cards.Controls.Remove(c);c.Dispose();}var list=games.Where(g=>g.Title.IndexOf(search.Text,StringComparison.CurrentCultureIgnoreCase)>=0).ToList();if(list.Count==0){var empty=new Label{Text=games.Count==0?L.T("Your first adventure starts here.\n\nAdd a folder containing your Saturn games.\nFormats: CUE + tracks, ISO, CHD.\n\nGames and BIOS are not included."):L.T("No games match your search."),AutoSize=true,Margin=new Padding(20,55,10,20),ForeColor=Ink,Font=new Font("Segoe UI",12)};cards.Controls.Add(empty);}foreach(var game in list){var item=new System.Windows.Forms.Panel{Size=new Size(220,322),Margin=new Padding(8),BackColor=Panel};var stripe=new Label{Text="S A T U R N",Dock=DockStyle.Top,Height=26,BackColor=Gold,ForeColor=Base,TextAlign=ContentAlignment.MiddleCenter,Font=new Font("Georgia",10)};item.Controls.Add(stripe);var pic=new PictureBox{Location=new Point(12,37),Size=new Size(196,172),SizeMode=PictureBoxSizeMode.Zoom,BackColor=Base};var cover=CoverPath(game);if(File.Exists(cover)){try{using(var im=Image.FromFile(cover))pic.Image=new Bitmap(im);}catch{}}pic.Disposed+=(a,b)=>{if(pic.Image!=null)pic.Image.Dispose();};if(pic.Image==null)pic.Paint+=(a,b)=>{using(var pen=new Pen(Gold,2)){b.Graphics.DrawEllipse(pen,61,46,74,74);b.Graphics.DrawEllipse(pen,91,76,14,14);} };item.Controls.Add(pic);var title=new Label{Text=game.Title,Location=new Point(12,219),Size=new Size(196,48),AutoEllipsis=true};tips.SetToolTip(title,game.Path);item.Controls.Add(title);var play=Button(L.T("▶ Play"),(a,b)=>Launch(game));play.Location=new Point(9,275);play.BackColor=Gold;play.ForeColor=Base;item.Controls.Add(play);var art=Button(L.T("Cover"),(a,b)=>SetCover(game));art.MinimumSize=new Size(70,36);art.Location=new Point(118,275);art.Width=90;item.Controls.Add(art);cards.Controls.Add(item);}cards.ResumeLayout();}
 string CoverPath(Game g){using(var sha=System.Security.Cryptography.SHA256.Create()){var hash=BitConverter.ToString(sha.ComputeHash(System.Text.Encoding.UTF8.GetBytes(g.Path.ToUpperInvariant()))).Replace("-","");return System.IO.Path.Combine(data,"covers",hash+".png");}}
 void SetCover(Game g){using(var d=new OpenFileDialog{Filter=L.T("Images|*.png;*.jpg;*.jpeg;*.bmp")})if(d.ShowDialog(this)==DialogResult.OK)try{Directory.CreateDirectory(System.IO.Path.Combine(data,"covers"));using(var image=Image.FromFile(d.FileName))image.Save(CoverPath(g),System.Drawing.Imaging.ImageFormat.Png);RenderGames();}catch(Exception e){Error(e);}}
 void Launch(Game g){try{if(playing!=null&&!playing.HasExited){MessageBox.Show(this,L.T("A Kronos session is already open. Close it before starting another game."));return;}var info=Engine.StartInfo(settings,g.Path);playing=Process.Start(info);if(settings.MinimizeOnPlay)WindowState=FormWindowState.Minimized;status.Text=L.T("Kronos started · ")+g.Title;var timer=new Timer{Interval=1000};timer.Tick+=(a,b)=>{if(playing==null||playing.HasExited){timer.Stop();timer.Dispose();if(settings.MinimizeOnPlay&&!IsDisposed){WindowState=FormWindowState.Normal;Activate();}status.Text=L.T("Session ended · back to library");}};timer.Start();}catch(Exception e){Error(e);}}
 public bool ReloadRequested;
 void Configure(){if(scanning)return;try{EnginePreferences.EnsureStopped();}catch(Exception e){Error(e);return;}if(playing!=null&&!playing.HasExited){MessageBox.Show(this,L.T("Close Kronos before continuing."));return;}using(var w=new PreferencesForm(settings,settingsPath)){if(w.ShowDialog(this)==DialogResult.OK){ReloadRequested=true;Close();}}}
 public void Snapshot(string path){Show();Application.DoEvents();var deadline=DateTime.UtcNow.AddSeconds(10);while(scanning && DateTime.UtcNow<deadline){Application.DoEvents();System.Threading.Thread.Sleep(10);}Application.DoEvents();using(var bmp=new Bitmap(Width,Height)){DrawToBitmap(bmp,new Rectangle(0,0,Width,Height));bmp.Save(path);}Close();}
}
static class Program {
 [STAThread]static int Main(string[] args){Application.EnableVisualStyles();Application.SetCompatibleTextRenderingDefault(false);if(args.Length>0&&args[0]=="--self-test")return Tests.Run();if(args.Length==2&&args[0]=="--screenshot"){using(var f=new MainForm())f.Snapshot(args[1]);return 0;}var root=AppDomain.CurrentDomain.BaseDirectory;var path=System.IO.Path.Combine(AppPaths.Initialize(root),"settings.xml");Settings settings;try{settings=Settings.Load(path);}catch{Application.Run(new MainForm());return 0;}L.Language=L.Normalize(settings.Language);if(args.Length==2&&args[0]=="--wizard-screenshots"){Directory.CreateDirectory(args[1]);using(var w=new SetupWizard(settings,path))w.CapturePages(args[1]);return 0;}if(args.Length==2&&args[0]=="--settings-screenshots"){Directory.CreateDirectory(args[1]);settings.Engine=System.IO.Path.Combine(root,"engine","kronos.exe");using(var p=new PreferencesForm(settings,path))p.CapturePages(args[1]);return 0;}if(!settings.SetupComplete){using(var w=new SetupWizard(settings,path))if(w.ShowDialog()!=DialogResult.OK)return 0;}bool again;do{using(var form=new MainForm()){Application.Run(form);again=form.ReloadRequested;}}while(again);return 0;}
}
static class Tests {
 public static int Run(){var dir=System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-fixtures-"+Guid.NewGuid().ToString("N"));Directory.CreateDirectory(dir);var report=new List<string>();try{var bin=System.IO.Path.Combine(dir,"épisode 1.bin");File.WriteAllText(bin,"fixture");var cue=System.IO.Path.Combine(dir,"Sakura test.cue");File.WriteAllText(cue,"FILE \"épisode 1.bin\" BINARY\n TRACK 01 MODE1/2352\n INDEX 01 00:00:00");Library.Validate(cue);report.Add("PASS CUE avec accents et espaces");var errors=new List<string>();var games=Library.Scan(new[]{dir,dir},errors);if(games.Count!=1||errors.Count!=0)throw new Exception("Scan incorrect");report.Add("PASS scan sans doublons ni pistes BIN isolées");File.Delete(bin);bool failed=false;try{Library.Validate(cue);}catch(IOException){failed=true;}if(!failed)throw new Exception("Piste manquante ignorée");report.Add("PASS piste CUE manquante détectée");var s=new Settings{Engine="C:\\Moteur Saturn\\kronos.exe",Bios="C:\\BIOS\\été.bin",Fullscreen=true};s.Folders.Add(dir);var config=System.IO.Path.Combine(dir,"settings.xml");s.Save(config);s.Save(config);s.Language="pt-BR";s.SetupComplete=true;s.Save(config);var loaded=Settings.Load(config);if(loaded.Language!="pt-BR"||!loaded.SetupComplete)throw new Exception("Language persistence");L.Verify();NewFeaturesTests.Run(dir);report.Add("PASS regional BIOS, input encoding, presets and slider UI");PreferencesTests.Run(dir);report.Add("PASS INI filters, preservation, conflicts and recursive scan");WizardTests.Run(dir);report.Add("PASS wizard navigation, five languages, finish and cancel");report.Add("PASS five language catalogs and setup persistence");var old=System.IO.Path.Combine(dir,"legacy.xml");File.WriteAllText(old,"<Saturn engine=\"\" bios=\"\" />");var legacy=Settings.Load(old);if(legacy.Language!="fr"||legacy.SetupComplete)throw new Exception("Legacy settings migration");report.Add("PASS legacy French settings migration");if(loaded.Bios!=s.Bios||loaded.Folders.Count!=1)throw new Exception("Persistence");report.Add("PASS sauvegarde et relecture configuration");s.Bios=System.IO.Path.Combine(dir,"test-bios.bin");File.WriteAllText(s.Bios,"fixture");var a=Engine.Arguments(s,cue);if(!a.Contains("--iso=\""+cue+"\"")||!a.Contains("--bios=\""+s.Bios+"\""))throw new Exception("Arguments");s.Hle=true;if(Engine.Arguments(s,cue).Contains("--bios="))throw new Exception("HLE");report.Add("PASS arguments Kronos BIOS et HLE");Library.Scan(new[]{System.IO.Path.Combine(dir,"missing")},errors);if(errors.Count!=1)throw new Exception("Dossier absent");report.Add("PASS dossier absent signalé");File.WriteAllLines(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-results.txt"),report);return 0;}catch(Exception e){report.Add("FAIL "+e);File.WriteAllLines(System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory,"test-results.txt"),report);return 1;}finally{Directory.Delete(dir,true);}}
}
}
